sudo: false
language: java
jdk:
  - openjdk8
  - oraclejdk8

services:
  - docker

env:
  global:
    # CC_TEST_REPORTER_ID
    secure: "apzhT0ZU5sIR/ndjCtnHmzfmJePOXle0DD8Y4a9kTvFPidk8/RET4+YmWhE1ij4GOActLpbEwivA2wrM/YyxbRTRY4dZro0iK+O0DvPYQTsiI/fYe4chNOSO0+IQ1MA/KJbJgeZKgBCM/uXNw2Evb+KwBqeN72Lx1K9/uK8VkI2aiqbw9W3gEcshVMWthTFiPSSZfqU14y9KHP8HoEZvGed7kFJFslsfqwgVRMP4cnrff3CEmQNardjY/aWgVKzuqMVEvnw2ER6K0ULYoQyUdqqngvaqv7bEtQLkwdiVbbphVRyTfUkHtqbStp4vasegzDiEf7RhatqPNLCxb5V/jJFa6/pMccvDESwefLJW7ZqBObdUjk4pHbrQoY+psCs5Rs6Y9p/hA6jomZKO3ipHF/kSnKDcLCueR9UMh0/JTkbbr4cNAnxwOjX3btCCKeqSxD/0BjLWUINrMfCuXBBt29EOs02wLlURtv5HZrPzrHFnqXy4lja3JOzhiqLjTURnFwzT0gysKWGMKx4PPiZr/BY35pX/Z9InRhlXyuh8pQ3BJnJ4y8OXh/IISB4R9YfiTm42UlhGJUT7w/NR8uwgUBiTu/QgNf5FoZrH4QMsbNPchKFzhpB8ucp6V9Chjg7+86i3/BHmQM65r7H9mP9iGaYXOTRiJCKDetbrMa1W8Cs="

script:
  # https://docs.travis-ci.com/user/docker/
  - docker pull jdanekrh/docker-alpine-openjdk-artemis-snapshot
  - docker run --rm -v`pwd`/scripts:/mnt -p 5672:5672 -p 61616:61616 -p 5673:5673 -p 61617:61617 --entrypoint ash jdanekrh/docker-alpine-openjdk-artemis-snapshot /mnt/entrypoint.sh amq7-server &
  - sleep 10
  - mvn clean package

  - java -jar cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar sender --address cli-activemq --log-msgs json --count 1
  - java -jar cli-activemq/target/cli-activemq-1.2.2-SNAPSHOT-LATEST.jar receiver --address cli-activemq --log-msgs json --count 1

  - java -jar cli-artemis-jms/target/cli-artemis-jms-1.2.2-SNAPSHOT-LATEST.jar sender --address cli-artemis-jms --log-msgs json --count 1
  - java -jar cli-artemis-jms/target/cli-artemis-jms-1.2.2-SNAPSHOT-LATEST.jar receiver --address cli-artemis-jms --log-msgs json --count 1

  - java -jar cli-qpid-jms/target/cli-qpid-jms-1.2.2-SNAPSHOT-LATEST.jar sender --address cli-qpid-jms --log-msgs json --count 1
  - java -jar cli-qpid-jms/target/cli-qpid-jms-1.2.2-SNAPSHOT-LATEST.jar receiver --address cli-qpid-jms --log-msgs json --count 1

after_success:
  - bash <(curl -s https://codecov.io/bash)
